### ISSUE TITLE
你的单词拼错啦

### ISSUE THREAD

**Issue by trickyEdecay** [Aspire-1/hello-world#1]
describe v. 描述

**Comment by trickyEdecay** [comment]
当你完成了你的修改之后..你要at我..告诉我你已经修改好了!然后关闭这个issues! @Aspire-1 

很多时候看到别人的软件有bug,我就在这里汇报,然后他们改完后会告诉我~让我去体验最新的东西

**Comment by Aspire-1** [comment]
@trickyEdecay i don't know how to reply to you
